"""Public plugin protocol and explicit registry surface."""

from .protocols import (
    EVIDENCE_STATUSES,
    PLUGIN_API_VERSION,
    PLUGIN_KINDS,
    PROTOCOL_METHODS,
    DiscoveryRequest,
    Evidence,
    ExecutionRequest,
    ExecutionResult,
    Plugin,
    PluginDescriptor,
    ProbeRequest,
    ProviderAdapter,
    RuntimeAdapter,
    SystemProbe,
    TransportAdapter,
    TransportRequest,
    ValidationRequest,
    ValidationResult,
    Validator,
)
from .registry import (
    ConformanceIssue,
    ConformanceReport,
    InvocationResult,
    PluginRegistry,
    PluginRegistryError,
    conformance_report,
)

__all__ = [
    "PLUGIN_API_VERSION",
    "PLUGIN_KINDS",
    "EVIDENCE_STATUSES",
    "PROTOCOL_METHODS",
    "PluginDescriptor",
    "ProbeRequest",
    "DiscoveryRequest",
    "ExecutionRequest",
    "TransportRequest",
    "ValidationRequest",
    "Evidence",
    "ExecutionResult",
    "ValidationResult",
    "Plugin",
    "SystemProbe",
    "ProviderAdapter",
    "RuntimeAdapter",
    "TransportAdapter",
    "Validator",
    "ConformanceIssue",
    "ConformanceReport",
    "InvocationResult",
    "PluginRegistry",
    "PluginRegistryError",
    "conformance_report",
]
